name: '${project_name}'
version: '${version}'
author: '${authors}'
description: '${project_description}'
website: '${homepage_url}'
main: '${group_id}.${project_id}.platforms.BukkitPlugin'
depends: [ TaterLib ]
softdepends: [ LuckPerms ]
folia-supported: true
commands:
  example:
    description: Example command
    usage: /example
    permission: example.command.example
    aliases: [ ex ]
